# Generated by Django 3.2.2 on 2023-08-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='publications/Esmeraldas-canton.jpg'),
        ),
    ]
