# Generated by Django 3.2.2 on 2023-08-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0002_alter_publication_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='imagen',
            field=models.ImageField(blank=True, default='publications/Esmeraldas-canton.jpg', null=True, upload_to='publications/'),
        ),
    ]
